config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :entries do
    resources :comments
  end

  root "sessions#home"

  #signup
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  #sessions
get '/login' => 'sessions#new'
post '/login' => 'sessions#create'
delete '/logout' => 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :entry
end

app/models/entry.rb
class Entry < ApplicationRecord
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :posts
  has_many :comments


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authenticate_user!
   redirect_to '/' if !current_user
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :authenticate_user!

  def index
    if params[:entry_id]
			@entry = Entry.find(params[:entry_id])
			@comments = Comment.all.where(entry_id: params[:entry_id])

      respond_to do |format|
				format.html {render partial: 'comments/ajax_comments', locals: { comments: @comments, entry: @entry}}
				format.json {render json: @comments}
			end

		else
			@comments = Comment.all
      respond_to do |f|
				f.html {render :index}
				f.json {render json: @comments}
			end
	end
  end

    def new
      @entry = Entry.find(params[:entry_id])
      @comment = @entry.comments.build
    end

    def create
      @entry = Entry.find(params[:entry_id])
      @comment = @entry.comments.build
      if @comment.update(comment_params)
         respond_to do |format|
				format.html {redirect_to entry_path(@entry)}
				format.json {render json: @comment}
			end
  else
    render :new
  end
end

    def show
      @comment = Comment.find(id: params[:id])
      respond_to do |f|
			f.html {render :show}
			f.json {render json: @comment}
		end
    end

private
		def comment_params
			params.require(:comment).permit(:entry_id, :content)
		end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
before_action :authenticate_user!

  def index
    @entries = Entry.all.order("created_at DESC")
    respond_to do |f|
      f.html { render :index }
      f.json { render json: @entries }
    end
  end

  def new
    @entry = Entry.new
  end

  def create
    @entry = Entry.new(entry_params)

    if @entry.save
      # respond_to do |f|
        # f.html { redirect_to entries_path }
        render json: @entry, status:201
      else
      render 'new'
    end

  end

  def edit
    set_entry
  end

  def update
    set_entry
    if @entry.update(entry_params)
      redirect_to @entry
    else
      render 'edit'
    end

  end

  def show
    set_entry
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @entry}
    end
  end

  def destroy
    set_entry
    @entry.destroy

    redirect_to entries_path
  end

  private

  def entry_params
    params.require(:entry).permit(:title, :content, :mood)
  end

  def set_entry
    @entry = Entry.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def home
end

def new
  @user = User.new
end

def create
  @user = User.find_by(username: params[:user][:username])
  if @user && @user.authenticate(params[:user][:password])
    session[:user_id] = @user.id
    redirect_to entries_path
  else
     flash[:error] = "Username or password was incorrect"
    redirect_to '/login'
  end
end


def destroy
  session.clear
  flash[:success] = "Successfully Logged Out!"
  redirect_to '/'
end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def new
  @user = User.new
end

def create
  @user = User.new(user_params)
  if @user.save
    session[:user_id] = @user.id
    redirect_to entries_path
  else
    render :new
  end
end


private

def user_params
  params.require(:user).permit(:username, :email, :password)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_ajax_comments.html.erb
<h1>Ajax comments call</h1>


<% comments.each do |comment| %>
	<br>
	<%= comment.content%>
	<br>
<% end %>

app/views/comments/index.html.erb
<h1>All Comments</h1>

<% @comments.each do |comment| %>
	Entry: <%= comment.entry.title%>
	Content: <%= comment.entry.content%>
	<br>
	<br>
	comment: <%= comment.content%>
	<br>
	<hr>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= form_for [@entry, @comment] do |f| %>
	<p><%= f.text_area :content %></p>

	<%= f.submit %>
<% end %>

app/views/entries/edit.html.erb
<h1>Edit Entry</h1>

<%= form_for @entry do |f| %>
	<p><%= f.label :title %></p>
	<p><%= f.text_field :title %></p>

	<p><%= f.label :content %></p>
	<p><%= f.text_area :content %></p>

	<%= f.submit %>
<% end %>

app/views/entries/index.html.erb
<h1>Journal Index</h1>

<br> <button id='sort-data'>Sort</button>

app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= form_for @entry do |f| %>
	<p><%= f.label :title %></p>
	<p><%= f.text_field :title %></p>

	<p><%= f.label :content %></p>
	<p><%= f.text_area :content %></p>

	<%= f.submit %>
<% end %>

<script type="text/javascript" charset="utf-8">
$(function () {
	$('form').submit(function(event) {
		event.preventDefault();
		var values = $(this).serialize();
		var posting = $.post('/entries', values);
		posting.done(function(data) {
			var entry = data;
		var entryTitle = entry["title"];
		var entryContent	= entry["content"];
		$("#newEntry").text("The entry " + entryTitle + " was created!" + "You wrote the following...     " + entryContent)
		});
	});
});
</script>

<div id="newEntry">

</div>

app/views/entries/show.html.erb
<h1>Entry Show</h1>
<h2>Title: <%= @entry.title%></h2>

<p><%= @entry.content%></p>

<p>Number of Comments: <%= @entry.comments.count%></p>




<br><%= link_to "New Comment", new_entry_comment_path(@entry), id: "new-comment" %>


<br> <button id='comment-data' data-id="<%=@entry.id%>">All Comments</button>

			<div id='ajax-comments'>

      </div>

<br><%= link_to "Edit Entry", edit_entry_path(@entry)%>
<br><%= link_to "Delete Entry", entry_path(@entry), method: :delete, data: { confirm: "Are you sure?" }%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reflection</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script type = "text/javascript" src = "//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js" ></script>
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application', 'entries' %>
  </head>

  <body>
    <%= yield %>
    <br>
      <%= link_to "Log Out", logout_path, method: :delete %> |
			<%= link_to "Main Page", entries_path %> |
			<%= link_to "New Entry", new_entry_path, class: 'ajax-new-entry' %>

			<br>

			<button id='entries-data'>All Entries</button>
			<div id='ajax-entries'></div>
			<br>

  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for(@user, url: signup_path) do |f| %>

  <%= f.label :username %>
  <%= f.text_field :username %>
  <br>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <%= f.submit "Sign Up" %>
<% end %>